apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-fitness-app
  namespace: default
spec:
  provider: azure
  secretObjects:
  # This section creates a regular Kubernetes Secret from the Key Vault data
  # so that the Pod can load it into environment variables easily.
  - secretName: fitness-app-env-secret
    type: Opaque
    data:
    # 'objectName' must match the secret name in Key Vault
    # 'key' will be the name of the environment variable in Kubernetes
    - objectName: CosmosDb
      key: MONGODB_URI
    - objectName: JwtSecret
      key: JWT_SECRET
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "e587635c-c1d4-482f-89bc-35e1010d01e6" # Replace with your Client ID
    keyvaultName: "key-vaultt" # Replace with your Key Vault name
    tenantId: "1721d0c3-fba6-4501-83b6-4afe93a160bb" # You can get this by running: az account show --query tenantId -otsv
    objects: |
      array:
        - |
          objectName: CosmosDb
          objectType: secret
          objectVersion: ""
        - |
          objectName: JwtSecret
          objectType: secret
          objectVersion: ""
